### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [kiranali/prj-rev-bwfs-dasmoto#6]
https://github.com/kiranali/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtShop/resources/css/style.css#L1-L22

Consider using the universal selector `*` instead of listing out every single tag that needs the default font. 

```css
* {
  font-family: Helvetica;
}
```
